[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
commands = ["npm ci"]

[phases.build]
commands = ["npm run build"]

[start]
cmd = "next start -p 3000 -H 0.0.0.0"

[environment]
PORT = "3000"
HOST = "0.0.0.0"